joshfarrant/shortcuts-js

- __tests__/actions/setAirplaneMode.spec.ts
- src/actions/index.ts
- src/actions/setAirplaneMode.ts
- src/interfaces/WF/WFWorkflowActionIdentifier.ts
Let's start with something simple here ✈️ 
Really like this!
> Add setAirplaneMode action

- .travis.yml
Currently the test script is not executed so we are currently doing nothing on CI.
This PR fixes it.
**Checks**
- _List added actions here..._
**Are you happy to be listed as a contributor in the actions list [here](https://github.com/joshfarrant/shortcuts-js/issues/6)?**
_Yes_
_If this is your first time contributing, I'd love to hear what you thought about the process. Was it easy/hard to find the information you were looking for? Did the Contributing Guide make sense? What were your stumbling blocks? Basically, any and all feedback is encouraged!_
> ci: run test script

- .npmignore
- src/actions/getContentsOfUrl.ts
- src/interfaces/WF/WFHTTPBodyType.ts
- src/interfaces/WF/WFHTTPMethod.ts
**Checks**
- None
Yes
- Removed some GitHub related files from the node module.
- Renamed `WFHttpMethod` to `WFHTTPMethod` to make it similar to `WFHTTPBodyType`.
- Added indentation to some types definitions.
> Updated .npmignore

- __tests__/actions/setBrightness.spec.ts
- src/actions/setBrightness.ts
**Checks**
- None
Yes
Fixes an unexpected behavior in `setBrightness()` action (#20).
> Fixed setBrightness to expect percentage value

- __tests__/actions/setBluetooth.spec.ts
- src/actions/index.ts
- src/actions/setBluetooth.ts
- src/interfaces/WF/WFWorkflowActionIdentifier.ts
**Checks**
- _setBluetooth_
_Yes_
_shortcuts-js_ is a very interesting project. The documentation is readable and clear.
> Add setBluetooth action

- CONTRIBUTING.md
- src/actions/addToVariable.ts
- src/actions/getVariable.ts
- src/actions/setVariable.ts
**Checks**
- None
Yes
- Updated some old documentation bits;
- Removed old references to JSDoc in `CONTRIBUTING.md`.
> Updated addToVariable, getVariable and setVariable documentation

- src/actions/getCurrentIpAddress.ts
**Checks**
This PR fixes a simple mistaken docstring.
> Fixed incorrect getCurrentIpAddress docstring

- __tests__/actions/openInBooks.spec.ts
- __tests__/actions/print.spec.ts
- __tests__/actions/quickLook.spec.ts
- src/actions/index.ts
- src/actions/openInBooks.ts
- src/actions/print.ts
- src/actions/quickLook.ts
- src/actions/setCellularData.ts
- src/actions/setWiFi.ts
- src/interfaces/WF/WFWorkflowActionIdentifier.ts
**Checks**
- _print_
- _quickLook_
- _openInBooks_
- _setCellularData_ (update comments)
- _setWiFi_ (update comments)
> Add print, quickLook & openInBooks actions

- src/actions/openInBooks.ts
- src/actions/print.ts
- src/actions/quickLook.ts
- src/actions/setCellularData.ts
- src/actions/setWiFi.ts
> Update actions description

- __tests__/actions/generateHash.spec.ts
- src/actions/generateHash.ts
- src/actions/index.ts
- src/interfaces/WF/WFHashType.ts
- src/interfaces/WF/WFWorkflowActionIdentifier.ts
- src/interfaces/WF/WFWorkflowActionParameters.ts
**Checks**
- `Generate Hash`
Yes
> Add generateHash action

- __tests__/actions/calculateStatistics.spec.ts
- src/actions/calculateStatistics.ts
- src/actions/index.ts
- src/interfaces/WF/WFStatisticsOperation.ts
- src/interfaces/WF/WFWorkflowActionIdentifier.ts
- src/interfaces/WF/WFWorkflowActionParameters.ts
**Checks**
- `Calculate Statistics`
Yes
> Add calculateStatistics action

- __tests__/actions/setDoNotDisturb.spec.ts
- src/actions/index.ts
- src/actions/setDoNotDisturb.ts
- src/interfaces/WF/AssertionType.ts
- src/interfaces/WF/WFWorkflowActionIdentifier.ts
- src/interfaces/WF/WFWorkflowActionParameters.ts
**Checks**
- `Set Do Not Disturb`
Yes
> Add setDoNotDisturb action

- __tests__/actions/pauseMusic.spec.ts
- __tests__/actions/setVolume.spec.ts
- __tests__/actions/skipBack.spec.ts
- __tests__/actions/skipForward.spec.ts
- src/actions/index.ts
- src/actions/pauseMusic.ts
- src/actions/setVolume.ts
- src/actions/skipBack.ts
- src/actions/skipForward.ts
- src/interfaces/WF/WFSkipBackBehavior.ts
- src/interfaces/WF/WFWorkflowActionIdentifier.ts
- src/interfaces/WF/WFWorkflowActionParameters.ts
**Checks**
- Pause Music
- Set Volume
- Skip Back
- Skip Forward
Yes
> Add Playback Actions

- __tests__/actions/airDrop.spec.ts
- __tests__/actions/getMapsURL.spec.ts
- __tests__/actions/markup.spec.ts
- src/actions/airDrop.ts
- src/actions/getMapsURL.ts
- src/actions/index.ts
- src/actions/markup.ts
- src/interfaces/WF/WFWorkflowActionIdentifier.ts
**Checks**
- _markup_
- _getMapsURL_
- _airDrop_
> Add markup, getMapsURL & airDrop actions

- __tests__/actions/createNote.spec.ts
- __tests__/actions/getMyShortcuts.spec.ts
- __tests__/actions/showInMaps.spec.ts
- __tests__/actions/tweet.spec.ts
- src/actions/ask.ts
- src/actions/chooseFromMenu.ts
- src/actions/createNote.ts
- src/actions/generateHash.ts
- src/actions/getMyShortcuts.ts
- src/actions/index.ts
- src/actions/postOnInstagram.ts
- src/actions/showInMaps.ts
- src/actions/tweet.ts
- src/interfaces/WF/WFWorkflowActionIdentifier.ts
**Checks**
- createNote
- showInMaps
- tweet
- getMyShortcuts
> Add createNote, showInMaps, tweet & getMyShortcuts actions

- __tests__/actions/showInMaps.spec.ts
- src/actions/matchText.ts
- src/actions/runJavascriptOnWebPage.ts
- src/actions/showInMaps.ts
- src/actions/showResult.ts
- src/interfaces/WF/WFMapsApps.ts
- src/interfaces/WF/WFWorkflowActionParameters.ts
**Checks**
Added `app` option to showInMaps action
Support for `Google Maps`, `Waze` and `Apple Maps` (default `''`)
Fixes #54
Also improved description for some actions
> Added app option to showInMaps action

- __tests__/actions/makeArchive.spec.ts
- __tests__/actions/urlEncode.spec.ts
- src/actions/index.ts
- src/actions/makeArchive.ts
- src/actions/urlEncode.ts
- src/interfaces/WF/WFArchiveFormat.ts
- src/interfaces/WF/WFWorkflowActionIdentifier.ts
- src/interfaces/WF/WFWorkflowActionParameters.ts
**Checks**
- Make Archive
- URL Encode
Yes
Fingers crossed this is all good <3
> Added Make Archive + URL Encode Actions

- __tests__/actions/getTimeBetweenDates.spec.ts
- src/actions/getTimeBetweenDates.ts
- src/actions/index.ts
- src/interfaces/WF/WFTimeUntilReferenceDate.ts
- src/interfaces/WF/WFTimeUntilUnit.ts
- src/interfaces/WF/WFWorkflowActionIdentifier.ts
- src/interfaces/WF/WFWorkflowActionParameters.ts
**Checks**
- getTimeBetweenDates
Yes!
Great experience w/ first contribution.  Was able to find everything I needed relatively easily (after a good initial deep dive).  What a cool project; glad to be a part of it!
Edit: Are you looking for one squashed commit per action add?
> Add getTimeBetweenDates action

- __tests__/actions/openURLs.spec.ts
- __tests__/actions/openURLsInChrome.spec.ts
- src/actions/index.ts
- src/actions/openURLsInChrome.ts
- src/interfaces/WF/WFWorkflowActionIdentifier.ts
**Checks**
**Added Actions**
- openURLsInChrome
> Add openURLsInChrome action

- __tests__/actions/editPythonistaScript.spec.ts
- __tests__/actions/runPythonistaScript.spec.ts
- src/actions/editPythonistaScript.ts
- src/actions/index.ts
- src/actions/runPythonistaScript.ts
- src/interfaces/WF/WFWorkflowActionIdentifier.ts
- src/interfaces/WF/WFWorkflowActionParameters.ts
**Checks**
- `Edit Script (Pythonista)`
- `Run Script (Pythonista)`
Yes
> Add Pythonista actions

- src/actions/index.ts
- src/actions/openApp.ts
- src/interfaces/WF/WFWorkflowActionIdentifier.ts
- src/interfaces/WF/WFWorkflowActionParameters.ts
I haven't written tests for the new action.
**Checks**
- Open App
Yes
> Add support for the Open App action.

- README.md
Minor PR to fix links to the contributing guide in the readme. ( 61a6494 )
> Fix links to contributing guide in readme links

- __tests__/actions/getCurrentLocation.spec.ts
- src/actions/getCurrentLocation.ts
- src/actions/index.ts
_Please delete all sections in italics before submitting this PR._
**Checks**
- getCurrentLocation
_Yes_ 
_If this is your first time contributing, I'd love to hear what you thought about the process. Was it easy/hard to find the information you were looking for? Did the Contributing Guide make sense? What were your stumbling blocks? Basically, any and all feedback is encouraged!_
> Get Current Location action added

- __tests__/actions/repeat.spec.ts
- __tests__/utils/withActionOutput.spec.ts
- __tests__/utils/withVariables.spec.ts
- src/actions/index.ts
- src/actions/repeat.ts
- src/interfaces/WF/WFWorkflowActionIdentifier.ts
- src/interfaces/WF/WFWorkflowActionParameters.ts
- src/utils/withActionOutput.ts
- src/variables.ts
_Please delete all sections in italics before submitting this PR._
- Repeat
_Yes_
As a newcomer to javascript and typescript, I was stuck for a while on how to run the tests. It may be useful to add the command `yarn test` to the Contributing Guide. Otherwise the guide was very helpful.
> Repeat action

- __tests__/actions/caseChange.spec.ts
- src/actions/changeCase.ts
- src/actions/index.ts
- src/interfaces/WF/WFCaseType.ts
- src/interfaces/WF/WFWorkflowActionIdentifier.ts
- src/interfaces/WF/WFWorkflowActionParameters.ts
**Checks**
- Change Case
_Yes_ 
_If this is your first time contributing, I'd love to hear what you thought about the process. Was it easy/hard to find the information you were looking for? Did the Contributing Guide make sense? What were your stumbling blocks? Basically, any and all feedback is encouraged!_
> Change Case added
